In [1]:
import pandas as pd

In [4]:
# Plug potential drug to model
# read data fitur drug
data_drug = pd.read_csv("Output/fitur_drug_klekota-roth_ap.csv", sep=",", header=0)
data_drug.head()

,smiles,idx_code,chembl_code,0,1,2,3,4,5,6,...,4850,4851,4852,4853,4854,4855,4856,4857,4858,4859
0,CCOC(=O)C1=C[C@@H](OC(CC)CC)[C@H](NC(C)=O)[C@@...,x,chembl1200340,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,[H][C@]1(OC(=C[C@H](NC(N)=N)[C@H]1NC(C)=O)C(O)...,x,chembl222813,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,CC(=O)NC([C@H]1CC(C(O)=O)C[C@@H]1N=C(N)N)C(=O)...,88428,chembl293591,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,CCN(CC)C(=O)[C@@H]1OC(C(O)O)=C[C@H](N=C(N)N)[C...,247120,chembl344548,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
#get feature and label only
data_drug_X = data_drug.iloc[:, 3:4863]
data_drug_X.head()

,0,1,2,3,4,5,6,7,8,9,...,4850,4851,4852,4853,4854,4855,4856,4857,4858,4859
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [6]:
import pickle

In [9]:
# 1. logistic regression standar model
#membuka kembali model untuk digunakan dalam prediksi senyawa baru
with open("Output/model_logistic_kk", "rb") as input_file:
    model_baru = pickle.load(input_file)

In [10]:
#menggunakan model tersimpan untuk prediksi
y_drug_pred_lr = model_baru.predict(data_drug_X)

In [11]:
y_drug_pred_lr

array([1, 1, 1, 1])

In [ ]:
######################################################

In [14]:
# 2. logistic regression optimize model
#membuka kembali model untuk digunakan dalam prediksi senyawa baru
with open("Output/model_logistic_optimize_kk", "rb") as input_file:
    model_baru_opt = pickle.load(input_file)

In [15]:
#menggunakan model tersimpan untuk prediksi
y_drug_pred_opt_lr = model_baru_opt.predict(data_drug_X)

In [16]:
y_drug_pred_lr

array([1, 1, 1, 1])